
/*
create database stock_dbb_statics;
use stock_dbb_statics

별도의 dbb에 반영할수 있게, dbb명은 추가 X

mysql -u root -p -D stock_dbb < maria_stock_init_statics.sql
*/

/*
일자별 로그보다는, 통계 데이터의 로그량이 더 많다. 
일별 단가 변화 통계
주별 단가 변화 통계 
월별 단가 변화 통계

주간 거래량 합계 통계
월간 거래량 합계 통계 => 이건 의미가 있을가.

일별 거래량 변화 통계
주간 거래량 변화 통계 => 하루 급등보다, 현재 누적 (문제는 기간으로 산정하면, 기간에 따라 오탐 가능성.)

TODO: 여기는 조금더 검토

*/

/** DROP TABLE

DROP TABLE PRICE_DAILY_CHANGE_STATICS_2012
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2013
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2014
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2015
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2016
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2017
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2018
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2019
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2020
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2021
DROP TABLE PRICE_DAILY_CHANGE_STATICS_2022

**/

/** DESC

DESC PRICE_DAILY_CHANGE_STATICS_2012
DESC PRICE_DAILY_CHANGE_STATICS_2013
DESC PRICE_DAILY_CHANGE_STATICS_2014
DESC PRICE_DAILY_CHANGE_STATICS_2015
DESC PRICE_DAILY_CHANGE_STATICS_2016
DESC PRICE_DAILY_CHANGE_STATICS_2017
DESC PRICE_DAILY_CHANGE_STATICS_2018
DESC PRICE_DAILY_CHANGE_STATICS_2019
DESC PRICE_DAILY_CHANGE_STATICS_2020
DESC PRICE_DAILY_CHANGE_STATICS_2021
DESC PRICE_DAILY_CHANGE_STATICS_2022

**/

---------------------------------------------------------------------------------------------------------------------------------------

-- 일별 단가 변화 통계, 2012 ~ 2022, 매년 1개 생성

/* 2012년 -------------------------------------------------------------------- */
    
/* 2012 일별 단가 변화 통계 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2012
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명*/
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2012_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2012(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2012_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2012(REG_DATE);


/* 2012 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2012
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2012_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2012(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2012_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2012(REG_DATE);

/* 2012 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2012
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2012_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2012(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2012_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2012(REG_DATE);

/* 2013년 -------------------------------------------------------------------- */

/* 2013 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2013
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2013_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2013(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2013_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2013(REG_DATE);


/* 2013 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2013
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2013_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2013(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2013_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2013(REG_DATE);

/* 2013 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2013
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2013_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2013(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2013_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2013(REG_DATE);


/* 2014년 -------------------------------------------------------------------- */

/* 2014 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2014
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2014(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2014(REG_DATE);


/* 2014 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2014
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2014_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2014(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2014_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2014(REG_DATE);

/* 2014 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2014
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2014_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2014(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2014_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2014(REG_DATE);

/* 2015년 -------------------------------------------------------------------- */

/* 2015 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2015
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2015_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2015(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2015_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2015(REG_DATE);

/* 2015 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2015
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2015_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2015(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2015_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2015(REG_DATE);

/* 2015 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2015
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2015_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2015(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2015_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2015(REG_DATE);

/* 2016년 -------------------------------------------------------------------- */

/* 2016 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2016
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2016_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2016(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2016_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2016(REG_DATE);

/* 2016 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2016
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2016_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2016(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2016_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2016(REG_DATE);

/* 2016 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2016
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2016_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2016(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2016_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2016(REG_DATE);


/* 2017년 -------------------------------------------------------------------- */

/* 2017 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2017
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2017_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2017(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2017_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2017(REG_DATE);


/* 2017 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2017
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2017_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2017(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2017_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2017(REG_DATE);

/* 2017 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2017
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2017_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2017(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2017_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2017(REG_DATE);

/* 2018년 -------------------------------------------------------------------- */

/* 2018 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2018
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2018_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2018(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2018_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2018(REG_DATE);


/* 2018 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2018
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2018_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2018(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2018_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2018(REG_DATE);

/* 2018 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2018
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2018_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2018(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2018_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2018(REG_DATE);

/* 2019년 -------------------------------------------------------------------- */

/* 2019 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2019
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2019_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2019(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2019_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2019(REG_DATE);

/* 2019 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2019
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2019_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2019(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2019_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2019(REG_DATE);

/* 2019 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2019
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2019_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2019(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2019_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2019(REG_DATE);

/* 2020년 -------------------------------------------------------------------- */

/* 2020 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2020
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2020_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2020(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2020_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2020(REG_DATE);

/* 2020 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2020
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2020_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2020(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2020_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2020(REG_DATE);

/* 2020 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2020
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2020_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2020(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2020_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2020(REG_DATE);

/* 2021년 -------------------------------------------------------------------- */

/* 2021 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2021
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2021_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2021(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2021_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2021(REG_DATE);

/* 2021 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2021
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2021_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2021(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2021_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2021(REG_DATE);

/* 2021 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2021
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2021_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2021(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2021_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2021(REG_DATE);

/* 2022년 -------------------------------------------------------------------- */

/* 2022 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2022
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2022_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2022(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2022_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2022(REG_DATE);


/* 2022 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2022
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2022_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2022(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2022_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2022(REG_DATE);

/* 2022 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2022
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2022_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2022(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2022_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2022(REG_DATE);

/* 2023년 -------------------------------------------------------------------- */

/* 2023 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2023
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2023_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2023(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2023_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2023(REG_DATE);


/* 2023 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2023
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2023_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2023(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2023_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2023(REG_DATE);

/* 2023 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2023
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2023_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2023(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2023_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2023(REG_DATE);


/* 2024년 -------------------------------------------------------------------- */

/* 2024 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2024
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2024_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2024(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2024_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2024(REG_DATE);


/* 2024 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2024
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2024_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2024(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2024_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2024(REG_DATE);

/* 2024 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2024
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2024_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2024(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2024_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2024(REG_DATE);


/* 2025년 -------------------------------------------------------------------- */

/* 2025 일별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2025
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2025_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2025(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_2025_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_DAILY_CHANGE_STATICS_2025(REG_DATE);


/* 2025 주별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2025
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2025_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2025(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_WEEK_CHANGE_2025_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_WEEK_CHANGE_STATICS_2025(REG_DATE);

/* 2025 월별 단가 변화 통계 */
CREATE TABLE STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2025
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	PRICE_CHANGE FLOAT(10,3) NOT NULL, /* 단가 변화값 */
	CURRENT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 현재값 */
	NEXT_PRICE INT NOT NULL DEFAULT 0, /* 단가, 다음값 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
);

CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2025_STATICS_STOCK_CODE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2025(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_MONTH_CHANGE_2025_STATICS_REG_DATE ON STOCK_DBB_STATICS.PRICE_MONTH_CHANGE_STATICS_2025(REG_DATE);

