
/*
create database stock_dbb_2;
create database stock_dbb_bulk;

별도의 dbb에 반영할수 있게, dbb명은 추가 X

mysql -u root -p -D stock_dbb < maria_stock_init_bulk_daily.sql
*/

/*
두번 실행할때의 처리, 만일 기존 테이블의 완전 삭제시 별도 drop 
mariadb는 대소문자를 가리지 않아, 대소문자 구문 무의미, 

-- 변수 선언.
SET @cur_db := 'stock_script_Test';
*/

/* dbscript 실행전, dbb는 미리 생성되어 있어야 한다.
 script에서 생성중, 존재하면 실행되지 않는다. (create or replace 구문 필요)
create database stock_dbb_bulk; */

USE STOCK_DBB_BULK;

SHOW TABLES;


/*---------------------------------------------------------------------------------------------------------------------------------------*/

/* 일자별 로그, 2012 ~ 2022, 매년 1개 생성 */
    
/* 2012 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2012   
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	UNIT_PRICE INT NOT NULL DEFAULT 0, /* 단가 */
	TRADE_VOLUME INT NOT NULL DEFAULT 0, /* 거래량 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
); /* ENGINE=INNODB DEFAULT CHARSET UTF8; */

-- 과거 INDEX 삭제

-- DROP INDEX UIX_BULK_DATE_2012_CODE_DATE_PRICE ON  DAILY_BULK_DATA_2012;
-- DROP INDEX UIX_BULK_DATE_2012_CODE_DATE_VOLUME ON  DAILY_BULK_DATA_2012;

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2012_CODE_DATE_PRICE ON STOCK_DBB_BULK.DAILY_BULK_DATA_2012(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2012_CODE_DATE_VOLUME ON STOCK_DBB_BULK.DAILY_BULK_DATA_2012(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2013 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2013
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	UNIT_PRICE INT NOT NULL DEFAULT 0, /* 단가 */
	TRADE_VOLUME INT NOT NULL DEFAULT 0, /* 거래량 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
); /* ENGINE=INNODB DEFAULT CHARSET UTF8; */

/* 과거 INDEX 삭제 */

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2013_CODE_DATE_PRICE ON STOCK_DBB_BULK.DAILY_BULK_DATA_2013(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2013_CODE_DATE_VOLUME ON STOCK_DBB_BULK.DAILY_BULK_DATA_2013(STOCK_CODE, REG_DATE, TRADE_VOLUME);


/* 2014 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2014
(
	STOCK_CODE VARCHAR(16) NOT NULL, /* 종목코드 */
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL, /* 등록일자 */
	UNIT_PRICE INT NOT NULL DEFAULT 0, /* 단가 */
	TRADE_VOLUME INT NOT NULL DEFAULT 0, /* 거래량 */

	PRIMARY KEY (STOCK_CODE, REG_DATE) /* 기본키 */
); /* ENGINE=INNODB DEFAULT CHARSET UTF8; */

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2014_CODE_DATE_PRICE ON DAILY_BULK_DATA_2014(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2014_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2014(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2015 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2015
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,   

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2015_CODE_DATE_PRICE ON DAILY_BULK_DATA_2015(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2015_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2015(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2016 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2016
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,        
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2016_CODE_DATE_PRICE ON DAILY_BULK_DATA_2016(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2016_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2016(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2017 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2017
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '',
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE) 
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2017_CODE_DATE_PRICE ON DAILY_BULK_DATA_2017(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2017_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2017(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2018 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2018
(
	STOCK_CODE VARCHAR(16) NOT NULL,  
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2018_CODE_DATE_PRICE ON DAILY_BULK_DATA_2018(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2018_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2018(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2019 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2019
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2019_CODE_DATE_PRICE ON DAILY_BULK_DATA_2019(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2019_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2019(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2020 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2020
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2020_CODE_DATE_PRICE ON DAILY_BULK_DATA_2020(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2020_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2020(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2021 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2021
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2021_CODE_DATE_PRICE ON DAILY_BULK_DATA_2021(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2021_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2021(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2022 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2022
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2022_CODE_DATE_PRICE ON DAILY_BULK_DATA_2022(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2022_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2022(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2023 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2023
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2023_CODE_DATE_PRICE ON DAILY_BULK_DATA_2023(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2023_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2023(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2024 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2024
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2024_CODE_DATE_PRICE ON DAILY_BULK_DATA_2024(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2024_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2024(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2025 일자별 로그 */
CREATE TABLE IF NOT EXISTS STOCK_DBB_BULK.DAILY_BULK_DATA_2025
(
	STOCK_CODE VARCHAR(16) NOT NULL,    
	STOCK_NAME VARCHAR(128) NOT NULL DEFAULT '', /* 종목명 */
	REG_DATE INT NOT NULL,       
	UNIT_PRICE INT NOT NULL DEFAULT 0,    
	TRADE_VOLUME INT NOT NULL DEFAULT 0,  

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2025_CODE_DATE_PRICE ON DAILY_BULK_DATA_2025(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2025_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2025(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* CREATE VIEW IF NOT EXISTS VIEW_DAILY_BULK_DATA AS
	SELECT * FROM DAILY_BULK_DATA_2012
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2013
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2014
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2015
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2016
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2017
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2018
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2019
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2020
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2021
	UNION ALL SELECT * FROM DAILY_BULK_DATA_2022; 
*/

