# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import hook_pb2 as hook__pb2
import util_modules.wins_manage_modules.ext_data_process_modules.command_agent_hook_data_server.grpc_modules.hook_pb2 as hook__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HookProxyStub(object):
    """service define
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HookBrowserMessage = channel.unary_unary(
                '/hook_proxy.HookProxy/HookBrowserMessage',
                request_serializer=hook__pb2.BrowserHookRequest.SerializeToString,
                response_deserializer=hook__pb2.BrowserHookResponse.FromString,
                _registered_method=True)
        self.HookLLMRequest = channel.unary_unary(
                '/hook_proxy.HookProxy/HookLLMRequest',
                request_serializer=hook__pb2.LLMRequest.SerializeToString,
                response_deserializer=hook__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.HookMCPCall = channel.unary_unary(
                '/hook_proxy.HookProxy/HookMCPCall',
                request_serializer=hook__pb2.MCPCallRequest.SerializeToString,
                response_deserializer=hook__pb2.MCPCallResponse.FromString,
                _registered_method=True)
        self.HookLLMStreamChunk = channel.unary_unary(
                '/hook_proxy.HookProxy/HookLLMStreamChunk',
                request_serializer=hook__pb2.LLMStreamChunkRequest.SerializeToString,
                response_deserializer=hook__pb2.LLMStreamChunkResponse.FromString,
                _registered_method=True)
        self.HookLLMResponse = channel.unary_unary(
                '/hook_proxy.HookProxy/HookLLMResponse',
                request_serializer=hook__pb2.LLMResponseRequest.SerializeToString,
                response_deserializer=hook__pb2.LLMResponseResponse.FromString,
                _registered_method=True)
        self.HookMCPResponse = channel.unary_unary(
                '/hook_proxy.HookProxy/HookMCPResponse',
                request_serializer=hook__pb2.MCPResponseRequest.SerializeToString,
                response_deserializer=hook__pb2.MCPResponseResponse.FromString,
                _registered_method=True)


class HookProxyServicer(object):
    """service define
    """

    def HookBrowserMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookLLMRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookMCPCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookLLMStreamChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookLLMResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookMCPResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HookProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HookBrowserMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.HookBrowserMessage,
                    request_deserializer=hook__pb2.BrowserHookRequest.FromString,
                    response_serializer=hook__pb2.BrowserHookResponse.SerializeToString,
            ),
            'HookLLMRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HookLLMRequest,
                    request_deserializer=hook__pb2.LLMRequest.FromString,
                    response_serializer=hook__pb2.LLMResponse.SerializeToString,
            ),
            'HookMCPCall': grpc.unary_unary_rpc_method_handler(
                    servicer.HookMCPCall,
                    request_deserializer=hook__pb2.MCPCallRequest.FromString,
                    response_serializer=hook__pb2.MCPCallResponse.SerializeToString,
            ),
            'HookLLMStreamChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.HookLLMStreamChunk,
                    request_deserializer=hook__pb2.LLMStreamChunkRequest.FromString,
                    response_serializer=hook__pb2.LLMStreamChunkResponse.SerializeToString,
            ),
            'HookLLMResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.HookLLMResponse,
                    request_deserializer=hook__pb2.LLMResponseRequest.FromString,
                    response_serializer=hook__pb2.LLMResponseResponse.SerializeToString,
            ),
            'HookMCPResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.HookMCPResponse,
                    request_deserializer=hook__pb2.MCPResponseRequest.FromString,
                    response_serializer=hook__pb2.MCPResponseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hook_proxy.HookProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hook_proxy.HookProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HookProxy(object):
    """service define
    """

    @staticmethod
    def HookBrowserMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookBrowserMessage',
            hook__pb2.BrowserHookRequest.SerializeToString,
            hook__pb2.BrowserHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookLLMRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookLLMRequest',
            hook__pb2.LLMRequest.SerializeToString,
            hook__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookMCPCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookMCPCall',
            hook__pb2.MCPCallRequest.SerializeToString,
            hook__pb2.MCPCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookLLMStreamChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookLLMStreamChunk',
            hook__pb2.LLMStreamChunkRequest.SerializeToString,
            hook__pb2.LLMStreamChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookLLMResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookLLMResponse',
            hook__pb2.LLMResponseRequest.SerializeToString,
            hook__pb2.LLMResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookMCPResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hook_proxy.HookProxy/HookMCPResponse',
            hook__pb2.MCPResponseRequest.SerializeToString,
            hook__pb2.MCPResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
