


/*
sqlite 통계 테이블 스키마

*/

---------------------------------------------------------------------------------------------------------------------------------------

-- 일별 단가 변화 통계, 2012 ~ 2022, 매년 1개 생성
    
/* 2012 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2012
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2012(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2012(REG_DATE);

/* 2013 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2013
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2013(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2013(REG_DATE);


/* 2014 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2014
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2014(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2014(REG_DATE);

/* 2015 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2015
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2015(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2015(REG_DATE);

/* 2016 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2016
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2016(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2016(REG_DATE);

/* 2017 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2017
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2017(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2017(REG_DATE);

/* 2018 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2018
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2018(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2018(REG_DATE);

/* 2019 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2019
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2019(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2019(REG_DATE);

/* 2020 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2020
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2020(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2020(REG_DATE);

/* 2021 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2021
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2021(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2021(REG_DATE);

/* 2022 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2022
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2022(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2022(REG_DATE);

/* 2023 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2023
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2023(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2023(REG_DATE);

/* 2024 일별 단가 변화 통계 */
CREATE TABLE PRICE_DAILY_CHANGE_STATICS_2024
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	PRICE_CHANGE REAL NOT NULL, -- 단가 변화값
	CURRENT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 현재값
	NEXT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가, 다음값

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
);

CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_STOCK_CODE ON PRICE_DAILY_CHANGE_STATICS_2024(STOCK_CODE);
CREATE INDEX IF NOT EXISTS IX_PRICE_DAILY_CHANGE_STATICS_REG_DATE ON PRICE_DAILY_CHANGE_STATICS_2024(REG_DATE);

COMMIT;