
/*

sqlite, database refactoring
mysql 과 동일한 스키마,index 지원
sql 문법의 상이점 보완
*/

---------------------------------------------------------------------------------------------------------------------------------------

-- 일자별 로그, 2012 ~ 2022, 매년 1개 생성
    
/* 2012 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2012   
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
); 


-- 과거 INDEX 삭제

-- DROP INDEX UIX_BULK_DATE_2012_CODE_DATE_PRICE ON  DAILY_BULK_DATA_2012;
-- DROP INDEX UIX_BULK_DATE_2012_CODE_DATE_VOLUME ON  DAILY_BULK_DATA_2012;

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2012_CODE_DATE_PRICE ON DAILY_BULK_DATA_2012(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2012_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2012(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2013 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2013
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
); -- ENGINE=INNODB DEFAULT CHARSET UTF8;

-- 과거 INDEX 삭제

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2013_CODE_DATE_PRICE ON DAILY_BULK_DATA_2013(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2013_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2013(STOCK_CODE, REG_DATE, TRADE_VOLUME);


/* 2014 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2014
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE) -- 기본키
); -- ENGINE=INNODB DEFAULT CHARSET UTF8;

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2014_CODE_DATE_PRICE ON DAILY_BULK_DATA_2014(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2014_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2014(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2015 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2015
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2015_CODE_DATE_PRICE ON DAILY_BULK_DATA_2015(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2015_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2015(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2016 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2016
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2016_CODE_DATE_PRICE ON DAILY_BULK_DATA_2016(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2016_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2016(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2017 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2017
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2017_CODE_DATE_PRICE ON DAILY_BULK_DATA_2017(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2017_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2017(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2018 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2018
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2018_CODE_DATE_PRICE ON DAILY_BULK_DATA_2018(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2018_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2018(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2019 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2019
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량 

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2019_CODE_DATE_PRICE ON DAILY_BULK_DATA_2019(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2019_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2019(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2020 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2020
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2020_CODE_DATE_PRICE ON DAILY_BULK_DATA_2020(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2020_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2020(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2021 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2021
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2021_CODE_DATE_PRICE ON DAILY_BULK_DATA_2021(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2021_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2021(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2022 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2022
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2022_CODE_DATE_PRICE ON DAILY_BULK_DATA_2022(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2022_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2022(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2023 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2023
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2023_CODE_DATE_PRICE ON DAILY_BULK_DATA_2023(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2023_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2023(STOCK_CODE, REG_DATE, TRADE_VOLUME);


/* 2024 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2024
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2024_CODE_DATE_PRICE ON DAILY_BULK_DATA_2024(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2024_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2024(STOCK_CODE, REG_DATE, TRADE_VOLUME);

/* 2025 일자별 로그 */
CREATE TABLE IF NOT EXISTS DAILY_BULK_DATA_2025
(
	STOCK_CODE TEXT NOT NULL, -- 종목코드
	STOCK_NAME TEXT NOT NULL DEFAULT '', -- 종목명
	REG_DATE INTEGER NOT NULL, -- 등록일자
	UNIT_PRICE INTEGER NOT NULL DEFAULT 0, -- 단가
	TRADE_VOLUME INTEGER NOT NULL DEFAULT 0, -- 거래량

	PRIMARY KEY (STOCK_CODE, REG_DATE)
);

CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2025_CODE_DATE_PRICE ON DAILY_BULK_DATA_2025(STOCK_CODE, REG_DATE, UNIT_PRICE);
CREATE INDEX IF NOT EXISTS UIX_BULK_DATE_2025_CODE_DATE_VOLUME ON DAILY_BULK_DATA_2025(STOCK_CODE, REG_DATE, TRADE_VOLUME);


-- CREATE VIEW IF NOT EXISTS VIEW_DAILY_BULK_DATA AS
-- 	SELECT * FROM DAILY_BULK_DATA_2012
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2013
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2014
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2015
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2016
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2017
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2018
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2019
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2020
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2021
-- 	UNION ALL SELECT * FROM DAILY_BULK_DATA_2022; 

-- SQLite는 COMMIT 미지원
COMMIT;